version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "grouch-message-function"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1oq8ho1pgifjt"
s3_prefix = "grouch-message-function"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
