AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  grouch-message-function

  Sample SAM Template for grouch-message-function

Resources:
  GrouchMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GrouchMessageFunction
      Handler: grouch.message.function.FunctionHandler
      Runtime: java11
      CodeUri: .
      Timeout: 30
      MemorySize: 1512
      Environment:
        Variables:
          FUNCTION_NAME: MessageFunction
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /v1/message
            Method: get