AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  grouch-message-function

  Sample SAM Template for grouch-message-function

Resources:
  GrouchMessageFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: java11-maven-v1
      DockerContext: .
      Dockerfile: Dockerfile
    Properties:
      FunctionName: GrouchMessageFunction
      Handler: grouch.message.function.FunctionHandler
      PackageType: Image
      CodeUri: .
      Timeout: 30
      MemorySize: 1512
      Environment:
        Variables:
          FUNCTION_NAME: MessageFunction
      Policies:
        - Statement:
            - Sid: LambdaInvokePolicy
              Effect: Allow
              Action: lambda:InvokeFunction
              Resource: "*"

Outputs:
  GrouchMessageFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt GrouchMessageFunction.Arn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-GrouchMessageFunction
  GrouchMessageFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt GrouchMessageFunction.Arn